### PR TITLE
Strict datatypes and normal-form convertion

### PR DESCRIPTION
**Pull request by jprupp**
Added instances of NFData for pretty much all data types. This allows for deepseq to force evaluation to normal form instead of just weak-head normal form as allowed by seq.
Most data types already had strict arguments, I set them where they were still missing.

### CODE REVIEW

**Comment by m0dev76** [comment]
It doesn't merge automatically. You may have to rebase on master.

**Comment by jprupp** [comment]
It seems good now, check the changes and ack if you're satisfied.

**Comment by m0dev76** [comment]
ACK

**Comment by sha49** [comment]
ACK

**Pull request merged**
