### PR TITLE
Update of Evaluator to support optionals flags.

### PR DESCRIPTION
**Pull request by lornap**
Adding Flags and nearly complete Flag handling to script Evaluator.  This allows updated test json files to be used from Bitcoin Core.

### CODE REVIEW

**Comment by jprupp** [comment]
ACK

**Comment by lornap** [comment]
The new script_(in)valid.json files do reveal some issues regarding how to handle weird signatures.  I’ve removed the failing tests for now.

**Comment by m0dev76** [comment]
I think you need to rebase this branch on your previous commit #120 so it can merge automatically.

**Comment by lornap** [comment]
Whoops.  I'm stepping all over myself here.  Rebased.

**Pull request merged**
