### PR TITLE
Fix script

### PR DESCRIPTION
**Pull request by OttoAllmendinger**
some edge cases found with QuickCheck

### CODE REVIEW

**Comment by OttoAllmendinger** [comment]
there may be more to come

**Comment by OttoAllmendinger** [comment]
This should be it for now. 

I have a suspicion that there are some other bugs, but I have to look at it again another time.

**Comment by m0dev76** [comment]
Nice fixes, thanks! ACK on my end.

**Comment by jprupp** [comment]
ACK

**Comment by sha49** [comment]
ACK

Thanks @OttoAllmendinger

**Pull request merged**
